---
title: "About me"
description: |
  Some additional details about me and why I'm doing this...
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I received my Ph.D. in Psychology from The University of Texas at Austin in 2006 (that's really a *long time ago*). My major course work was completed in Behavioral Neuroscience, with a minor in Statistics. It was during that time I realized he have a love of answering questions using the statistical techniques that I was learning. I also realized that I very much enjoyed teaching. After graduating I quickly turned I passion for both teaching and statistics into a position as a Statistical Consultant for The University of Texas. Since that time I've helped develop new statistics courses to take advantage of new teaching techniques (like a MOOC on edX), I've helped graduate students with their research questions (though my Department's Statistical Consulting Service), and I've helped undergraduate students learn this amazing tool called data analysis (with a few classes here and there).